# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2

# Mod Properties
mod_version = 2.3.4
maven_group = nl.enjarai
archives_base_name = omnihopper
modid = omnihopper

publish_target_min=26.1.2
publish_target_max=26.1.2
mod_modrinth=i2u9r3li
mod_curseforge=610606
mod_github=enjarai/OmniHopper
git_branch=26.1/dev

# Dependencies
fabric_version=0.150.0+26.1.2
# https://github.com/gniftygnome/cooldown-coordinator/releases
# https://maven.enjarai.dev/#/mirrors/net/gnomecraft/cooldown-coordinator
cooldowncoordinator_version=0.10.0-alpha.1
# https://maven.enjarai.dev/#/releases/nl/enjarai/cicada-lib
cicada_version=0.15.1+26.1
